### ISSUE TITLE
Specify sample size from two samples

### ISSUE THREAD

**Issue by cfbeuchel** [ash-res/prop-coloc#2]
Hi!

thanks a lot for making this method available here!

I was wondering whether it shouldn't be possible to supply two sample sizes to the `prop.coloc` function when data from different studies is used for the two traits? I am running an analysis with some example data at the moment and am unable to figure out the details. Analysing data from multiple samples is supported as far as I understand? I am unsure of what exactly happens under the hood with the sample size, except that it is involved in many of the calculations, but manually specifying two samples sizes will lead to unexpected behavior.

I would appreciate any advice on this. Can I use the function for colocalization analysis from multiple samples and if yes, which sample size(s) should I specify? Thank you in advance!

Best wishes,

Carl

**Comment by ash-res** [comment]
> Hi!
> 
> thanks a lot for making this method available here!
> 
> I was wondering whether it shouldn't be possible to supply two sample sizes to the `prop.coloc` function when data from different studies is used for the two traits? I am running an analysis with some example data at the moment and am unable to figure out the details. Analysing data from multiple samples is supported as far as I understand? I am unsure of what exactly happens under the hood with the sample size, except that it is involved in many of the calculations, but manually specifying two samples sizes will lead to unexpected behavior.
> 
> I would appreciate any advice on this. Can I use the function for colocalization analysis from multiple samples and if yes, which sample size(s) should I specify? Thank you in advance!
> 
> Best wishes,
> 
> Carl

Dear Carl, 

Many thanks for trying to apply the method! You’re right — the test was designed for the one-sample setting where genetic associations with both traits are measured from the same sample. But we have now updated the package so that a two-sample version runs if you supply two sample sizes as n=c(n1,n2), where n1 is the sample size for trait 1 and n2 is the sample size for trait 2. For this two-sample version, the assumption is that the data from the two studies are measured from non-overlapping samples. 

So hopefully with this newer version, you should now be able to apply the method with your two-sample example data. You can reinstall the package in R using the command
 devtools::install_github("ash-res/prop-coloc”)

Many thanks,
Ash

**Comment by cfbeuchel** [comment]
Thank you very much for the explanation and for implementing this!

This resolves this issue.

Best wishes,
Carl
